#!/usr/bin/env sh


cd sim
echo "[\033[34msetup\033[0m] Building simulator"
make sim || exit
cd ../mjdep
echo "[\033[34msetup\033[0m] Building minijazz dependencies handler"
make mjdep || exit
cd ../minijazz/src
echo "[\033[34msetup\033[0m] Building minijazz to netlist compiler"
ocamlbuild mjc.byte || exit
cd ../../jupiter
echo "[\033[34msetup\033[0m] Building assembler"
make jupiter || exit
echo "[\033[34msetup\033[0m] Assembling clock program"
./jupiter prog_clock.s
cd ../micro
echo "[\033[34msetup\033[0m] Making final microprocessor netlist (mono core)"
make main || exit
echo "[\033[34msetup\033[0m] Making final microprocessor netlist (dual core part 1)"
make split/main1 || exit
echo "[\033[34msetup\033[0m] Making final microprocessor netlist (dual core part 2)"
make split/main2 || exit
cp main_full.sch.net main_full.sch.net.backup # Pour pas être obligé de refaire le setup après avoir fait un make clean
echo "[\033[34msetup\033[0m] Ready to run !"
