CMX=debug.cmx netlist_ast.cmx netlist_parser.cmx netlist_lexer.cmx netlist.cmx \
netlist_printer.cmx graph.cmx scheduler.cmx core.cmx sim_lexer.cmx main.cmx
GEN=netlist_parser.ml netlist_parser.mli netlist_lexer.ml sim_lexer.ml
LIBS = unix.cmxa
BIN=sim


NO_COLOR=\033[0m
OK_COLOR=\033[32;01m
ERROR_COLOR=\033[31;01m
WARN_COLOR=\033[33;01m
HIGHLIGHT_COLOR=\033[1m

all: $(BIN)
	@echo "$(HIGHLIGHT_COLOR)  ./$(BIN) test/ram.net$(NO_COLOR)"
	@./$(BIN) test/ram.net
	@echo "$(HIGHLIGHT_COLOR)  cat output.sim$(NO_COLOR)"
	@cat output.sim


$(BIN): $(CMX)
	@echo "Linking for $(BIN)..."
	@ocamlopt -o $(BIN) $(LIBS) $(CMX)
	@echo "$(OK_COLOR)Done.$(NO_COLOR)"

.SUFFIXES: .mli .ml .cmi .cmx .mll .mly

.mli.cmi:
	ocamlopt -c $<

.ml.cmx: 
	ocamlopt -c $<

.mll.ml:
	ocamllex $<

.mly.ml:
	menhir $<

.mly.mli:
	menhir $<

.PHONY: clean

clean:
	@echo "Cleaning directory..."
	@rm -v -f .depend *.cmi *.o *.automaton *~ $(CMX) $(GEN)
	@echo "$(OK_COLOR)Done.$(NO_COLOR)"

.depend: $(GEN)
	rm -f .depend
	ocamldep *.mli *.ml > .depend

ifneq ($(MAKECMDGOALS),clean)
include .depend
endif

