#!/usr/bin/env sh

# Mono core simulation
#../sim/sim --sim-only --async -rom ../jupiter/prog_clock.bin ../micro/main_full.sch.net.backup

# Dual core simulation
taskset -c 0 ../sim/sim --sim-only --async -rom ../jupiter/prog_clock.bin ../micro/split/main1_full.sch.net | taskset -c 1 ../sim/sim --sim-only ../micro/split/main2_full.sch.net

# Remote simulation (sur une meilleure machine)
#ssh elmichel@trolle.ens.fr "(cd sysdig/projet/final;./core)"



# Note: pour le test en fullspeed, retirer le flag --async

