#!/usr/bin/env sh

# Tests
##../sim/sim ../sim/test/test.net 2> /dev/null
## Pour bfmachine :
## ../sim/sim -rom ../micro/bfmachine.bin ../micro/bfmachine_full.net 2> /dev/null | ../sim/sim ../micro/convert7seg_full.net 2> /dev/null




# Usual simulation
#../sim/sim --sim-only -rom ../jupiter/prog_clock.bin ../micro/main_full.sch.net.backup

# Dual core simulation
taskset -c 0 ../sim/sim --sim-only -rom ../jupiter/prog_clock.bin ../micro/split/main1_full.sch.net | taskset -c 1 ../sim/sim --sim-only ../micro/split/main2_full.sch.net
