#!/usr/bin/env sh


# Horloge de l'ordinateur
#python ../input/clock.py


# Horloge externe (lecture sur le port série)
stty -F /dev/ttyACM0 9600 cs8 -cstopb -parenb && # setup serial port
cat < /dev/ttyACM0


